### ISSUE TITLE
Video and sound get desynchronized overtime

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/picodrive-irixxxx#2]
Video and sound get desynchronized overtime. The sound then gets late. It does not occur on RG350P with 1.97.
Tested on firmware 2.1.0 and PicoDrive 1.98 (early build). Same issue happens with default 1.93 version.

Expected behavior:
Video and sound should stay synchronized overtime.

Steps to reproduce:

1. Play any game on PicoDrive (any system) a few minutes or let the demo play WITHOUT pressing "Menu" key
2. Notice that image and sound are desynchronized (sound is late)
3. Press Menu key twice (open/close)
4. Notice that it's now synchronized again

**Comment by Michel-FK** [comment]
Fixed in commit https://github.com/FunKey-Project/picodrive-irixxxx/commit/0b95bad314e16e36d116c01f96a1145a868d0efe

**Comment by DrUm78** [comment]
Fixed and verified. We might need to find a better way than resyncing SDL audio every 5 minutes though, but at least that's a working temporary workaround.

**Comment by DrUm78** [comment]
@Vincent-FK Real fix is here guys (thanks to @irixxxx !): https://github.com/DrUm78/libpicofe/commit/184534ec801f071fe1f230771791c6b128b5c36d#diff-3dfd4e98180d80f7833fe58076b5430b3e94362bcd9555e1e0ac40bc442a8766.
No more desync, awesome. :)

**Comment by Vincent-FK** [comment]
This is awesome, thanks guys !

------ Original Message ------
From: "DrUm78" ***@***.***>
To: "FunKey-Project/picodrive-irixxxx" 
***@***.***>
Cc: "Vincent-FK" ***@***.***>; "Mention" 
***@***.***>
Sent: 11/7/2021 3:23:24 AM
Subject: Re: [FunKey-Project/picodrive-irixxxx] Video and sound get 
desynchronized overtime (#2)

>
***@***.*** <https://github.com/Vincent-FK> Real fix is here guys 
>(thanks to @irixxxx <https://github.com/irixxxx> !): 
***@***.***
