### ISSUE TITLE
[Regression][32X] Rendering mode stays displayed at the bottom left of the screen

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/picodrive-irixxxx#3]
Rendering mode stays displayed at the bottom left of the screen for 32X games (not Genesis nor Sega CD). Please note that this bug does not occur with default 1.93 version (rendering mode disappears from screen after game start) nor on RG350.
Tested with PicoDrive 1.98 early build and firmware 2.1.0.

Expected behavior:
Rendering mode should disappear after game boot

Workaround:
Pressing MENU button twice makes it disappear

Steps to reproduce:
1. Launch any 32X games (not 32X/Sega CD though) with PicoDrive 1.98 early build
2. Notice that the rendering mode stays displayed at the bottom left of the screen ("[...]ate" standing for "accurate")

![IMG_0035](https://user-images.githubusercontent.com/46139740/113473407-965baf00-9469-11eb-813f-57da8cace0eb.PNG)

**Comment by Michel-FK** [comment]
Fixed in commit https://github.com/FunKey-Project/picodrive-irixxxx/commit/0b95bad314e16e36d116c01f96a1145a868d0efe

**Comment by DrUm78** [comment]
Fixed verified!
